### ISSUE TITLE
Not an issue but a thank you

### ISSUE THREAD

**Issue by abresler** [jpneto/Markdowns#1]
This is one of the best tutorial repos for any language anywhere, makes it better for all of us who love R that it happens to be in the language we love the most.  Please keep adding more if you can and thank you for sharing these with the world they are all truly fantastic.

**Comment by jpneto** [comment]
Dear Alex,

Thanks for your kind words. These markdowns have been my way to understand R and the intersection of Stats&ML, either by testing other people's code or by writing my own. And it's great that they can help other people like you. We all take much from the net, it's only fair to give back the little that we can.

Cheers,
