### ISSUE TITLE
LaTeX not displaying on your web page

### ISSUE THREAD

**Issue by keevee09** [jpneto/Markdowns#2]
Your page here:
http://www.di.fc.ul.pt/~jpn/r/fourier/fourier.html
Is not rendering LaTeX code, rather it is displaying raw LaTeX code.
I downloaded the Rmd and csv files and managed to "knitHTML" and "knitPDF" with LaTeX displaying correctly. The only fault in my attempt was your accented name.
Thank you for a very useful tutorial (I have sent a link to my son who is studying physics at school and writing an assignment on guitar string tension and resulting tones.

**Comment by jpneto** [comment]
Thanks for the warning. Sometimes, old versions stop working, not sure why. I will update it in a few days.

Cheers,

keevee09 notifications@github.com escreveu:
