### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by cloudcell** [jpneto/Markdowns#3]
In your first example, did you intend to use

``` r
exp(-gamma * norm(as.matrix(x),"F") )
```

or

``` r
exp(-gamma * norm(as.matrix(x),"F")^2 )
```

i.e. the squared norm instead of just a simple euclidean distance?

I am asking this because it looks odd as you use the squared norm everywhere else and I don't see any special emphasis on a simple euclidean distance in your document (also here http://www.di.fc.ul.pt/~jpn/r/rbf/rbf.html).

Thank you very much in advance.

**Comment by jpneto** [comment]
Hi

Yes, it is a typo. The only thing that will change are the initial plots.
Below, I don't use that first rbf.gauss() to perform the classification.

Thanks, I'll change it soon,

João

**Comment by jpneto** [comment]
Made the correction. Also, I rewrote some mathjax formulas that weren't rendering.
